bookyToursProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import i18n
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('homepage.urls')),
    path('', include('themedTour.urls')),
    path('', include('personalTour.urls')),
    path('', include('components.urls')),
    path('', include('userProfile.urls')),
    path('', include('adminPanel.urls')),
    path('', include('supplier.urls')),
    path('', include('registration.urls')),
    path('',include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"




urlpatterns = [

path('cart/<int:id>/<int:hotel_id>', views.AddToCart.as_view(), name='addcart'),
path('cartremove/<int:product_id>',views.CartRemove.as_view(),name='cartremove'),
path('cartcar/<int:id>', views.AddToCartCar.as_view(), name='addcartcar'),

]

components/urls.py
from django.urls import path
from . import views

app_name = "components"

urlpatterns = [
    path("about/",views.about_view,name="about"),
    path("contact/", views.contact_view, name="contact"),
    path("faq/",views.faq_view,name="faq"),
    # path("question/",views.faq_question,name="faqQuestion"),
    path('privacy_policy', views.privacy_policy, name='privacyPolicy'),
    path('terms_and_conditions', views.terms_and_conditions, name='termsAndConditions'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path("", views.home_view, name="homepage"),
]

themedTour/urls.py
from django.urls import path
from . import views

app_name = "themedTour"


urlpatterns = [
    path("packchoice", views.themed_tour, name="packchoice"),
    path("thankyou", views.thankyou, name="thankyou"),

    path("singlepack/<int:id>", views.themed_single, name="themedsingle"),
    path('themedreview/<int:id>', views.themed_review, name='themedreview'),
    path("packorder/<int:id>", views.pack_order, name='packorder'),
    path("getorder/<int:id>", views.get_order, name='getorder'),
]

themedTour/models.py
from django.db import models
from adminPanel.models import Country
from registration.models import Account
from django.core.validators import MinValueValidator


class ThemedPack(models.Model):
	user = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
	pack_name = models.CharField(max_length=200)
	description = models.TextField()
	country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
	price = models.DecimalField(max_digits=50, decimal_places=2)
	picture1 = models.ImageField(upload_to='images/themedpack', default='images/brand-2.jpg')
	picture2 = models.ImageField(upload_to='images/themedpack', default='images/brand-2.jpg')
	small_video = models.FileField(upload_to="themedvideos")
	big_video = models.FileField(upload_to="themedvideos")
	trip_variety = models.ForeignKey(to='adminPanel.ThemedPackVariety', null=True, blank=True, on_delete=models.SET_NULL)
	NUMBER_OF_TRAVEL_CHOICES = (
		('1', '1'),
		('2', '2'),
		('3', '3'),
		('4', '4'),
		('5', '5'),
		('6', '6'),
		('7', '7'),
		('8', '8'),
		('9', '9'),
		('10', '10'),
		)
	number_of_travelers = models.CharField(max_length=100, choices = NUMBER_OF_TRAVEL_CHOICES)
	number_of_days = models.ForeignKey(to="adminPanel.ThemedPackDuration", on_delete=models.CASCADE)
	start_date = models.DateField()
	end_date = models.DateField()
	permission = models.BooleanField(default=False)
	notification = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Themed Pack"

	def __str__(self):
		return self.pack_name


class ThemedDaysDescription(models.Model):
	pack_connect_day = models.ForeignKey(ThemedPack, on_delete=models.CASCADE)
	description = models.TextField()

	def __str__(self):
		return self.pack_connect_day.pack_name


class ThemedPackReview(models.Model):
	pack = models.ForeignKey(ThemedPack, on_delete=models.CASCADE)
	user = models.ForeignKey(Account, on_delete=models.CASCADE)
	comment = models.TextField()
	stars = models.SmallIntegerField(default=5)
	permition = models.BooleanField(default=False)
	notification = models.BooleanField(default=False)

	def __str__(self):
		return self.user.email

	class Meta:
		verbose_name_plural = "Themed Pack Reviews"


class OrderedThemedPack(models.Model):
	user = models.ForeignKey(Account, on_delete=models.CASCADE)
	pack = models.ForeignKey(ThemedPack, on_delete=models.CASCADE)
	order_start_date = models.DateField()
	order_end_date = models.DateField()
	order_travelers = models.PositiveIntegerField(validators=[MinValueValidator(1)])

	def __str__(self):
		return self.pack.pack_name

themedTour/forms.py
from django import forms
from .models import ThemedPackReview, OrderedThemedPack


class ThemedReviewForm(forms.ModelForm):
    class Meta:
        model = ThemedPackReview
        fields = ('comment',)

        comment = forms.CharField(
                error_messages={
               'required': 'Please enter your TRAKI'
                })

        # def check_comment(self):
        #     commet = self.cleaned_data.get("comment")
        #     if comment=="":
        #         return forms.ValidationError("this is pizdec") 


class OrderedThemedPackForm(forms.ModelForm):
    class Meta:
        model = OrderedThemedPack
        fields = ('order_start_date', 'order_end_date', 'order_travelers')

themedTour/views.py
from django.shortcuts import render, redirect
from adminPanel.models import Country, FooterDescription, ThemedPackVariety
from .models import ThemedPack, ThemedDaysDescription, ThemedPackReview, OrderedThemedPack
from .forms import ThemedReviewForm, OrderedThemedPackForm
from datetime import timedelta, date, datetime
from adminPanel.models import ThemedPackReservation, City, ThemedPackDuration, DefaultPriceAdd
from django.template.defaulttags import register
from django.contrib import messages
from django.core.exceptions import ValidationError

# ============== for for range loop============
@register.filter
def get_range(value):
    return range(value)
# ===============================================


def themed_tour(request):
	default_price = DefaultPriceAdd.objects.get(id=1)
	country = Country.objects.all()
	themed_pack = ThemedPack.objects.all()
	trip_pack_varieties = ThemedPackVariety.objects.all()
	cities = City.objects.all()
	durations = ThemedPackDuration.objects.all().order_by("duration")
	themed_pack_dict = {}
	for i in themed_pack:
		themed_pack_dict[i]=round((float(i.price)+float(default_price.add_price))/4.07, 2)
	
	context = {
		'countries': country,
		'themedpack': themed_pack,
		'varieties' : trip_pack_varieties,
		'cities':cities,
		'durations':durations,
		'default_price':default_price,
		'themed_pack_dict':themed_pack_dict,
	}
	return render(request, 'themedTour/archive_themed.html', context)


def themed_single(request, id):
	themed_pack = ThemedPack.objects.get(id=id)
	footer = FooterDescription.objects.get(id=1)
	days = ThemedDaysDescription.objects.filter(pack_connect_day=id)
	reviews = ThemedPackReview.objects.filter(pack_id=id)
	# current_time=date.today()
	# if request.user.is_authenticated:
	# 	ordered_packs = OrderedThemedPack.objects.filter(user=request.user)	
	# else:
	# 	ordered_packs = OrderedThemedPack.objects.all()	
	context = {
		'pack': themed_pack,
		'footer': footer,
		'days': days,
		'reviews': reviews,
		# 'ordered_packs':ordered_packs,
		# 'current_time':current_time,

	}

	return render(request, "themedTour/pack_single.html", context)

def thankyou(request):
	
	return render(request, "themedTour/thankyoupage.html")


def themed_review(request, id):
	if request.user.is_authenticated:
		tour = ThemedPack.objects.get(id=id)
		if request.method == 'POST':
			form = ThemedReviewForm(request.POST or None)
			if form.is_valid():
				data = form.save(commit=False)
				data.comment = form.cleaned_data.get("comment")
				data.user = request.user
				data.pack = tour
				data.save()

				return redirect('themedTour:themedsingle', id)
			# else:
			# 	print(form.errors,"====================================")
				
			# 	messages.error(request, "SHEAVSE!")

			# 	return redirect('userProfile:userreservation')
		else:
			form = ThemedReviewForm()

		
		return render(request, 'homepage/homepage.html', {'form': form})

	else:
		return redirect('accounts/login')


def pack_order(request, id):
	pack = ThemedPack.objects.get(id=id)
	context = {
		'pack': pack,
	}
	return render(request, 'themedTour/pack_order.html', context)

 
def get_order(request, id):
	if request.user.is_authenticated:
		pack = ThemedPack.objects.get(id=id)
		if request.method == "POST":
			form = OrderedThemedPackForm(request.POST or None)
			dates = ThemedPackReservation.objects.filter(pack_id=id)
			if form.is_valid():
				#===================Getting dates for loop=================

				get_start_date = datetime.strptime(request.POST.get("order_start_date"),'%Y-%m-%d')
				order_startdate = datetime.date(get_start_date)
				get_end_date = datetime.strptime(request.POST.get("order_end_date"),'%Y-%m-%d')
				order_enddate = datetime.date(get_end_date)

				#====================  end dates  ============================

				order = form.save(commit=False)
				
				for day in range((order_enddate - order_startdate).days+1):
					tourorderdate = order_startdate + timedelta(day)
					for qs in dates:
						if tourorderdate==qs.date:
							check_quantity = qs.quantity-int(request.POST.get("order_travelers"))
							if check_quantity>=0:
								order.user = request.user
								order.pack = pack
							else:
								form = OrderedThemedPackForm()
								return redirect('themedTour:themedsingle', id)


				order.save()
				

				for day in range((order_enddate - order_startdate).days+1):
					tourorderdate = order_startdate + timedelta(day)
					for qs in dates:
						if tourorderdate == qs.date:
							left_quantity = qs.quantity-int(order.order_travelers)
							updated_reservation = ThemedPackReservation.objects.get(pack=qs.pack, date=qs.date)
							updated_reservation.quantity = left_quantity
							updated_reservation.save()
				return redirect('themedTour:thankyou')
			else:
				form = OrderedThemedPackForm()
			return render(request, 'themedTour/pack_single.html', {'form':form})
	else:
		return redirect('themedTour:themedsingle', id)

themedTour/templates/themedTour/pack_order.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<style>
  img.card_img {
    width: 66px;
}
.cartpages .cart table tr td {
    text-align: center;
    height: 84px;
    box-shadow: 1px 0px 18px 0px #0000001f;
}
.custom-control-input:checked ~ .custom-control-label::before{
  border-color: #DFB610;
background-color: #DFB610;
}
.themed_product img{
  width: 100%;
}
.description{
  margin-top: 10px;
}
.description p{
  margin-bottom: 5px;
}
.product_inner{
  border-radius: 11px;
display: flex;
box-shadow: 2px 3px 13px 0px #0000000f;
overflow: hidden;
}
ul.list-group.mb-3 {
  margin-top: 22px;
 }
 .order_submit_form {
   margin-top: 20px;
  font-size: 15px;
  font-weight: 500;
  background-color: #DFB610;
  color: #fff;
  padding: 12px 24px;
  border-radius: 5px;
  -webkit-transition: .9s;
  -o-transition: .9s;
  transition: .9s;
}
.order_submit_form:hover{
  color: #fff;
}
.images_pay img{
  width: 42%;
}
.images_pay{
  width: 100%;
  margin-top:25px;
}
.billing_address label{
  margin:10px 0 5px;
}
.billing_address input{
  width: 80%;
}
.product_inner h2{
  padding: 15px 0 0;
  font-size: 18px;
}
.main_checkout{
  box-shadow: 1px 6px 13px 8px #00000012;
  width: 100%;
  margin: 25px auto;
  padding: 30px 10px;
  border-radius: 15px;
}
</style>
    <div class="container">
        <div class="py-5 text-center">
          
          <h2>Checkout Page</h2>
          <p class="lead"></p>
        </div>
        <form action="{% url 'themedTour:getorder' pack.id %}" method="post" style="padding: 0 25px">
          {% csrf_token %}
        <div class="row main_checkout">
          <div class="col-offset-2 col-md-5 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center ">
              <h4 class="mb-3">Your Cart</h4>
              <span class="badge badge-secondary badge-pill cart_number"></span>
            </h4>
      
            <div class="cartpages">
              <div class="cart">
               
                <table style="width: 100%;"></table>

                <div class="row themed_product no-gutters">
                  <div class="product_inner">
                  <div class="col-md-5 no-gutters nopadding">
                    <img src="{% static 'images/brand-2.jpg' %}" alt="">
                  </div>
                  <div class="col-md-7" style="padding-right: 0;">
                    <h2>Tbilisi Golden hotel</h2>
                    <div class="description">
                    <p>Price</p>
                    <span id='pricethemed'>50$</span>
                    </div>
                  </div>
                  </div>
                </div>
              </div>

            </div>
            <ul class="list-group mb-3">
              
           
            
              <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <span id='pricethemedTotal'>$50<strong class="reservation_price"></strong></span>
              </li>
            </ul>
            <div class="terms_condition">
            <input type="checkbox" class="form-group" id="terms_condition">
            <label for="terms_condition">
              I Agree <a href="#">Terms and Condition</a>
            </label>
            </div>
            <button type="submit" class="btn  order_submit_form">Checkout</button>
            <div class="images_pay">
           <img src="{% static 'images/MasterCard_credit_cards_and_Visa_If_you_apply_for_both.jpg' %}" alt="">
           </div>
          </div>
          <div class="col-md-7 order-md-1 billing_address">
            <h4 class="mb-3">Billing address</h4>
           <div class="flex">
             <div >
              <label for="startdate"> Start Date</label>
              <input type="date" name="order_start_date" class="form-control order_input_form" id='startdate'>
              <label for="startdate"> End Date</label>
              <input type="date" name="order_end_date" class="form-control order_input_form" id='endtdate'>
              <label for="Quantity"> Quantity</label>
              <div id="packnumber_days" style="display: none;">{{ pack.number_of_days }} </div>
              <input type="number" name="order_travelers" class="form-control order_input_form" id='Quantity'>
            </div>
          </div>
          </div>
        </div>
      </form>
        </div>
      
      </div>
      <script src="{% static 'js/manual/themedcheckout.js' %}"></script>

{% endblock %}

themedTour/templates/themedTour/pack_single.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- inly in thsi page -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
<!-- inly in thsi page -->
    <!-- banner -->
        <section id="banner_pack">
            <video width="400"  autoplay loop muted>
                <source src="{{ pack.big_video.url }}" type="video/mp4">
            </video>
            
        </section>
        <div id="banner_bottom_pack">
            <div class="shape_bottom">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">
                    <path class="elementor-shape-fill" opacity="0.33" d="M473,67.3c-203.9,88.3-263.1-34-320.3,0C66,119.1,0,59.7,0,59.7V0h1000v59.7 c0,0-62.1,26.1-94.9,29.3c-32.8,3.3-62.8-12.3-75.8-22.1C806,49.6,745.3,8.7,694.9,4.7S492.4,59,473,67.3z"></path>
                    <path class="elementor-shape-fill" opacity="0.66" d="M734,67.3c-45.5,0-77.2-23.2-129.1-39.1c-28.6-8.7-150.3-10.1-254,39.1 s-91.7-34.4-149.2,0C115.7,118.3,0,39.8,0,39.8V0h1000v36.5c0,0-28.2-18.5-92.1-18.5C810.2,18.1,775.7,67.3,734,67.3z"></path>
                    <path class="elementor-shape-fill" d="M766.1,28.9c-200-57.5-266,65.5-395.1,19.5C242,1.8,242,5.4,184.8,20.6C128,35.8,132.3,44.9,89.9,52.5C28.6,63.7,0,0,0,0 h1000c0,0-9.9,40.9-83.6,48.1S829.6,47,766.1,28.9z"></path>
                </svg>
            </div>
        </div>
    <!-- banner -->
    <!-- section_why_us -->
        <div class="spicer_section"></div>
        <section id="Interesting_facts">
            <div class="container">
                <div class="section_facts">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="column_fact">
                                <div class="column_fact_inner">
                                    <div class="column_fact_section">
                                        <div class="social">
                                            <ul>
                                                <li><i class="fab fa-facebook-f"></i></li>
                                                <li><i class="fab fa-instagram"></i></li>
                                                <li><i class="fab fa-linkedin-in"></i></li>
                                            </ul>
                                        </div>
                                        <div class="location">
                                        <h6>
                                            <i class="fas fa-map-marker-alt"></i>
                                            <span>Tbilisi Georgia</span>
                                        </h6>
                                        <h3>Take A Tour</h3>
                                    <h2>{{ pack.pack_name }} </h2>
                                    </div>
                                    </div>
                                    
                                
                            </div>
                            </div>
                        </div>
                        <div class="col-md-4 ">
                            <div class="column_inner">
                           
                            <div class="column_img">
                               <img src="{{ pack.picture1.url }}" alt="">
    
                            </div>
                            
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="column_inner">
                                <div class="spicer_section"></div>
                                 <div class="column_img">
                                   <img src="{{ pack.picture2.url }}" alt="">
        
                                </div>
                                
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!--end  section_why_us -->

    <!-- section Experience -->
    <div class="spicer_section"></div>
    <section id="services_single_pack">
        <div class="container">
            <div class="row">
                <div class="service col-lg-4 col-12 text-center">
                    <div class="service_inner">
                        <i class="fas fa-headset"></i>
                        <div class="title">
                            <h3>Experienced Guides</h3>
                            <p>Lorem ipsum dolor sit amet cotetur adiing.</p>
                        </div>
                    </div>
                </div>
                <div class="service col-lg-4 col-12 text-center">
                    <div class="service_inner">
                        <i class="far fa-comment-dots"></i>
                        <div class="title">
                            <h3>Experienced Guides</h3>
                            <p>Lorem ipsum dolor sit amet cotetur adiing.</p>
                        </div>
                    </div>
                </div>
                <div class="service col-lg-4 col-12 text-center">
                    <div class="service_inner">
                        <i class="fas fa-restroom"></i>
                        <div class="title">
                            <h3>Experienced Guides</h3>
                            <p>Lorem ipsum dolor sit amet cotetur adiing.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--section Experience -->

    <!-- Tour Details -->
    <div class="spicer_section"></div>
    <section id="Tour_Details">
        <div class="container">
            <div class="section_inner">
                <div class="row">
                    <div class="left_side col-lg-5 col-md-12">
                        <div class="title">
                            <h2>Tour Details</h2>
                        </div>
                    </div>
                    <!-- tour Details -->
                    <div class="right_side col-lg-7 col-md-12">
                        {% for day in days %}
                        <div class="accordion-wrapper">
                            <button class="accordion"><h3>Day {{ forloop.counter }}</h3></button>
                            <div class="details">
                             <p>
                              {{ day.description }}
                             </p>
                            </div>
                          </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="spicer_section"></div>
    <!-- endTour Details  -->

    <!-- testimonial carousel -->
    <section id="testimonial carousel">
        <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="owl-carousel client-testimonial-carousel">
                    {% for review in reviews %}
                    {% if review.permition %}
                    <div class="single-testimonial-item">
                        <div class="image">
                        <img src="{% static 'images/PR-021-SI-01_05_12-539.png' %}" alt="">
                        </div>
                       
                            <div class="description">
                                <h6>{{ review.review_name }}</h6>
                                {% for star in review.stars|get_range %}
                                    <i class="fas fa-star"></i>
                                {% endfor %}
                                <p>{{ review.comment }}</p>
                            </div>
                       
                    </div>
                    {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
   
</div>

    </section>
    <div class="spicer_section"></div>
    <!-- testimonial carousel -->


    <!--write review-->

    <section id="faq_question">
            <div class="container">
                <div class="Question_inner single_review">
                    <h2>{% trans 'Write Review' %}</h2>
                    <div class="form_faq">
                        <form action="{% url 'themedTour:themedreview' pack.id %}" method="Post" id="ratingForm">
                            {% csrf_token %}
                        <fieldset class="rating">
                            <h4>Rate </h4>
                            <input type="radio" id="star5" name="stars" value="5" /><label for="star5" title="Rocks!">5 stars</label>
                            <input type="radio" id="star4" name="stars" value="4" /><label for="star4" title="Pretty good">4 stars</label>
                            <input type="radio" id="star3" name="stars" value="3" /><label for="star3" title="Meh">3 stars</label>
                            <input type="radio" id="star2" name="stars" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
                            <input type="radio" id="star1" name="stars" value="1" /><label for="star1" title="Sucks big time">1 star</label>
                        </fieldset>
                            <div >
                                <label for="Question">Your Review</label>
                                <textarea name="comment" class="form-control " id="Question" placeholder="Here you can leave your question"></textarea>
                            </div>
                            <div class="Send">
                                <input type="submit" value="Send">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section> 
    <!--write review -->

<!-- 
    <div class="reservation_none">
        <span>You can not leave the review before tour is started</span>
    </div> -->


<!-- bottom booking -->
<section id="booking_bottom">
    <div class="container" style="height: 100%;">
        <div class="section_inner">
            <div class="Total_cost">
                <p>Total Cost: <span>€ {% widthratio pack.price 4 1 %}</span></p>
            </div>
           
                <a href="{% url 'themedTour:packorder' pack.id %}" id="packid"> {% url 'themedTour:packorder' pack.id %}</a>
           
            {% if request.user.is_authenticated %}
                <div class="booking"  >
                    <a href="{% url 'themedTour:packorder' pack.id %}" id="confirmClickActionElementId">
                    Book Now
                    </a>
                </div>
            {% else %}
                <div class="booking"  >
                    <a href="" data-toggle="modal" data-target="#login_signUp" id="confirmClickActionElementId">
                    Book Now
                    </a>
                </div>
                {% url 'themedTour:packorder' pack.id %}
            {% endif %}
        </div>
    </div>
</section>
<!-- only in this page -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="{% static 'js/manual/testimonial.js' %}"></script>
<!-- only in this page -->
<!-- bottom booking -->
{% endblock %}

themedTour/templates/themedTour/thankyoupage.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}


<div class="thank_you_page text-center">
    <h1 class="display-3">Thank You!</h1>
    <p class="lead"><strong>Please check your email</strong> </p>
    <hr>
    <p>
      Having trouble? <a href="{% url 'components:contact' %}">Contact us</a>
    </p>
    <p class="">
      <a class="btn  btn-sm lead_read" href="{% url 'homepage:homepage' %}" role="button">Continue to homepage</a>
    </p>
  </div>



{% endblock %}