bookyToursProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import i18n
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('homepage.urls')),
    path('', include('themedTour.urls')),
    path('', include('personalTour.urls')),
    path('', include('components.urls')),
    path('', include('userProfile.urls')),
    path('', include('adminPanel.urls')),
    path('', include('supplier.urls')),
    path('', include('registration.urls')),
    path('',include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"




urlpatterns = [

path('cart/<int:id>/<int:hotel_id>', views.AddToCart.as_view(), name='addcart'),
path('cartremove/<int:product_id>',views.CartRemove.as_view(),name='cartremove'),
path('cartcar/<int:id>', views.AddToCartCar.as_view(), name='addcartcar'),

]

registration/urls.py
from django.urls import path
from . import views

app_name = "registration"

urlpatterns = [
    path('signup', views.sign_up, name='signUp'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_page, name='logout'),
    path('login_redirect/<slug:email>', views.login_redirect, name='loginRedirect'),
]

themedTour/urls.py
from django.urls import path
from . import views

app_name = "themedTour"


urlpatterns = [
    path("packchoice", views.themed_tour, name="packchoice"),
    path("thankyou", views.thankyou, name="thankyou"),

    path("singlepack/<int:id>", views.themed_single, name="themedsingle"),
    path('themedreview/<int:id>', views.themed_review, name='themedreview'),
    path("packorder/<int:id>", views.pack_order, name='packorder'),
    path("getorder/<int:id>", views.get_order, name='getorder'),
]

userProfile/urls.py
from django.urls import path
from . import views

app_name = "userProfile"

urlpatterns = [
#customer

    path("customerprofile/<int:id>", views.customer_profile, name="customerProfile"),
    path("ratepartners", views.rate_booky_partners, name="ratepartners"),
    path("reservation", views.UserReservations.as_view(), name="userReservation"),

#supplier

    path('supplierprofile/<int:id>', views.supplier_profile, name='supplierProfile'),
    path('supplierpayments', views.supplier_payments, name='supplierPayments'),
    path('supplieritems', views.supplier_items, name='supplierItems'),

#PDF
    path('supplierpayments/pdf/<int:id>',views.GeneratePdf.as_view(), name='generatePdf'),

#supplier themed pack

    path('supplieritem/<int:id>', views.supplier_item_pack, name='supplierItem'),
    path('supplierpackedit/<int:id>', views.edit_supplier_themed_pack, name='supplierPackEdit'),
    path('editsupplierpackdescription/<int:id>/<int:findex>', views.edit_supplier_themed_pack_description, name='editSupplierPackDescription'),
    path('suppliercalendarprice/<int:id>', views.supplier_price_edit, name='supplierCalendarPrice'),
    path('suppliercalendarquantity/<int:id>', views.supplier_quantity_edit, name='supplierCalendarQuantity'),
    path('supplieraddpack', views.supplier_themed_pack_add, name='supplierAddPack'),
    path('supplierdescriptionadd/<int:id>', views.supplier_themed_pack_description_add, name='supplierDescriptionAdd'),
    path('supplierpackreservation/<int:id>', views.supplier_themed_pack_reservation, name='supplierPackReservation'),

#supplier accomodation

    path('supplieraccommodationadd', views.supplier_accommodation_add, name='supplierAccommodationAdd'),
    path('supplieraccommodationedit/<int:id>', views.supplier_accommodation_edit, name='supplierAccommodationEdit'),

#supplier hotel

    path('supplierhotel/<int:id>', views.supplier_item_hotel, name='supplierHotel'), 
    path('edithotel/<int:acc_id>/<int:hotel_id>', views.edit_hotel_description, name='editHotel'),
    path('supplierhoteladd/<int:id>', views.supplier_hotel_add, name='supplierHotelAdd'),

#supplier apartment

    path('supplierapartment/<int:id>', views.supplier_item_apartment, name='supplierApartment'),
    path('supplierapartmentadd/<int:id>', views.supplier_apartment_add, name='supplierApartmentAdd'),

#supplier car

    path('suppliercar/<int:id>', views.supplier_item_car, name='supplierCar'),
    path('suppliercaradd', views.supplier_car_add, name='supplierCarAdd'),

#supplier other things
    path('roomplanning', views.room_planning, name='roomPlanning'),
    path('supplierlogin', views.supplier_login, name='supplierLogin'),
    # path('themedreview/<int:id>', views.themed_review, name='themedreview'),

]

userProfile/models.py
from django.db import models

# Create your models here.

userProfile/views.py
from django.shortcuts import render, redirect
from themedTour.models import OrderedThemedPack, ThemedPack, ThemedPackReview, ThemedDaysDescription
from adminPanel.models import Country, FooterDescription, ThemedPackReservation
from personalTour.models import Accommodation, AccommodationReview, Car, CarReview, Hotel, AccommodationOrder, Apartment, OrderCar,HotelOrder
from .forms import ThemedReviewForm, SupplierThemedPackForm, SupplierAccomodationForm, SupplierHotelForm, \
                    SupplierApartmentForm, SupplierCarForm, SupplierThemedDaysDescriptionForm
from adminPanel.forms import ThemedDaysDescriptionForm, ThemedPackPriceForm, ThemedPackTravelersQuantityForm
import datetime
from datetime import timedelta, date, datetime
from django.contrib import messages
from django.db.models import Avg
from django.forms.formsets import formset_factory
from registration.models import Account
from registration.forms import UserChangeForm
from django.views import View

def customer_profile(request, id):
    user = Account.objects.get(id=id)
    form = UserChangeForm(instance=user)

    if request.method == "POST":
        form = UserChangeForm(request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            data = form.save(commit=False)
            data.is_supplier = False
            data.is_active = True
            data.save()
            
            return redirect('userProfile:customerProfile', id)
        else:
            print(form.errors)

    context = {
        'form':form,
        'user':user,
    }

    return render(request, 'userProfile/customer_profile.html', context)


def user_reservation(request):

    ordered_packs = OrderedThemedPack.objects.filter(user=request.user)
    packs = ThemedPack.objects.all()
    current_time=date.today()
   
    context = {
        
        'ordered_packs':ordered_packs,
        'current_time': current_time,
    }
    return render(request, 'userProfile/reservation.html', context)

class UserReservations(View):
    def get(self,request):
        return render(request, 'userProfile/reservation.html', {})


def rate_booky_partners(request):

    context = {
        
    }
    return render(request, 'userProfile/rate_booky_partners.html', context)


# def themed_review(request, id):
#     tour = ThemedPack.objects.get(id=id)
#     print("vax chemi")
#     if request.method == 'POST':
#         form = ThemedReviewForm(request.POST or None)
#         print("valodia")
#         if form.is_valid():
#             print("vinki")
#             data = form.save(commit=False)
#             data.user = request.user
#             data.pack = tour
#             data.save()

#             return redirect('userProfile:userreservation', id)

#         else:
#             print("tinki")
#             messages.error(request, "SHEAVSE!")

#             return redirect('userProfile:userreservation', id)

#     else:
#         form = ThemedReviewForm()

#     return render(request, 'userProfile/reservation.html', {'form': form})


def supplier_profile(request, id):
    user = Account.objects.get(id=id)
    form = UserChangeForm(instance=user)

    if request.method == "POST":
        form = UserChangeForm(request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            data = form.save(commit=False)
            data.is_supplier = True
            data.is_active = True
            data.save()
            
            return redirect('userProfile:supplierProfile', id)
        else:
            print(form.errors)
       
    context = {
        'form':form,
        'user':user,
    }

    return render(request, 'userProfile/supplier_profile.html', context)

import pdfkit
def supplier_payments(request):
    print(request.user)

    unpaid_hotels=HotelOrder.objects.filter(supplier=request.user,payment_status='unpaid')
    paid_hotels = HotelOrder.objects.filter(supplier=request.user, payment_status='paid')

    context = {'unpaid_hotels': unpaid_hotels,
               'paid_hotels': paid_hotels}




    return render(request, 'userProfile/my_payments.html',context)

from django.http import HttpResponse
from django.views.generic import View
from datetime import date
from .utils import render_to_pdf #created in step 4

class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        obj = HotelOrder.objects.get(id=id, supplier=self.request.user, payment_status='paid')

        data = {
            'obj':obj,
             'today': date.today(),
             'amount': 39.99,
            'customer_name': 'Cooper Mann',
            'order_id': 1233434,
        }


        print(obj)
        pdf = render_to_pdf('userProfile/invoice.html', data)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" % ("12341231")
            content = "inline; filename=%s" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename=%s" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")
        #return HttpResponse(pdf, content_type='application/pdf')



def supplier_items(request):
    supplier_themed_packs = ThemedPack.objects.filter(user=request.user)
    themed_packs = {}
    for i in supplier_themed_packs:
        try:
            themed_packs[i] = round(ThemedPackReview.objects.filter(pack=i).aggregate(Avg('stars')).get('stars__avg'),1)
        except TypeError:
            themed_packs[i] = 0
    try:
        avarange_themed_pack_stars = sum(themed_packs.values())/len(themed_packs)
    except ZeroDivisionError:
        avarange_themed_pack_stars = 0

    print(themed_packs)
    supplier_accommodations = Accommodation.objects.filter(user=request.user, accommodation_type="1")
    accommodations = {}
    for i in supplier_accommodations:
        nom = i.hotel_set.filter(hotel_name=i)
        try:
            accommodations[i] = ((round(AccommodationReview.objects.filter(accommodation=i).aggregate(Avg('stars')).get('stars__avg'),1)),nom)
        except TypeError:
            accommodations[i] = (0, nom)

    try:
        avarange_accommodation_stars = tuple(accommodations.values())[0][0]/len(accommodations)
    except:
        avarange_accommodation_stars = 0


    supplier_appartment = Accommodation.objects.filter(user=request.user, accommodation_type="2")
    apartments = {}
    print(apartments)
    for i in supplier_appartment:
        toa = i.apartment_set.get(apartment_name=i)
        try:
            apartments[i] = ((round(AccommodationReview.objects.filter(accommodation=i).aggregate(Avg('stars')).get('stars__avg'),1)), toa)
        except TypeError:
            apartments[i] = (0, toa)
    print(apartments)
    try:
        avarange_apartment_stars = tuple(apartments.values())[0][0]/len(apartments)
    except:
        avarange_apartment_stars = 0


    supplier_cars = Car.objects.filter(user=request.user)
    cars = {}
    for i in supplier_cars:
        try:
            cars[i] = round(CarReview.objects.filter(car=i).aggregate(Avg('stars')).get('stars__avg'),1)
        except TypeError:
            cars[i] = 0
    try:
        avarange_car_stars = sum(cars.values())/len(cars)
    except ZeroDivisionError:
        avarange_car_stars = 0
    if len(apartments)==0:
        apartments = False
    if len(cars)==0:
        cars = False
    if len(themed_packs)==0:
        themed_packs = False
    if len(accommodations)==0:
        accommodations = False
    print(apartments)
    context = {
        'themed_packs':themed_packs,
        'accommodations':accommodations,
        'apartments':apartments,
        'cars':cars,
        'avarange_themed_pack_stars':avarange_themed_pack_stars,
        'avarange_accommodation_stars':avarange_accommodation_stars,
        'avarange_apartment_stars':avarange_apartment_stars,
        'avarange_car_stars':avarange_car_stars,
    }

    return render(request, 'userProfile/my_items.html', context)

#====================THEMED PACK========================================
def supplier_item_pack(request, id):
    supplier_themed_pack = ThemedPack.objects.get(id=id)
    form = SupplierThemedPackForm(instance=supplier_themed_pack)
    day_description = ThemedDaysDescription.objects.filter(pack_connect_day=id)
    form_day_description = {}
    for i in range(supplier_themed_pack.number_of_days.duration):
        form_day_description[i] = ThemedDaysDescriptionForm(instance=day_description[i])
    calendar = ThemedPackReservation.objects.filter(pack_id=id)
    form_price = ThemedPackPriceForm()
    form_quantity = ThemedPackTravelersQuantityForm()
    context = {
        'supplier_themed_pack':supplier_themed_pack,
        'form':form,
        'form_day_description':form_day_description,
        'calendar':calendar,
        'form_price':form_price,
        'form_quantity':form_quantity,
    }

    return render(request, 'userProfile/themed_pack/edit_my_pack.html', context)


def edit_supplier_themed_pack(request, id):
    if request.method=='POST':
        pack = ThemedPack.objects.get(id=id)
        form = SupplierThemedPackForm(request.POST,files=request.FILES, instance=pack)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
                
            return redirect('userProfile:supplierItem', id)


def edit_supplier_themed_pack_description(request, id,findex):
    if request.method=='POST':
        pack = ThemedPack.objects.get(id=id)
        description = ThemedDaysDescription.objects.filter(pack_connect_day=id)

        for i in range(len(description)):
            if i==findex:
                form = ThemedDaysDescriptionForm(request.POST,instance=description[i])

        if form.is_valid():
            data = form.save(commit=False)
            data.save()

userProfile/templates/userProfile/my_items.html
{% extends 'userProfile/base_supplier.html' %}
{% block content %}
{% load static %}
<script>
    $(function(){
        $('.stars').stars();
        
    });
</script>
<div class="addallcarand col-md-12 col-sm-12">
    <div class="addallbuttonbook">
        <a  class="btn btn-link collapsed buttonmy_items addbuttonall"  href="{% url 'userProfile:supplierAddPack' %}"> Add Themed Pack </a>
    </div>
    
    <div class="addallbuttonbook">
        <a class="btn btn-link collapsed buttonmy_items addbuttonall"  href="{% url 'userProfile:supplierAccommodationAdd' %}"> Add Accommodation </a>
    </div>

    <div class="addallbuttonbook">
        <a class="btn btn-link collapsed buttonmy_items addbuttonall"  href="{% url 'userProfile:supplierCarAdd' %}"> Add Car </a>
    </div>
</div>
                <!-- Begin Page Content -->
                <div class="container-fluid my_item" >
                    <!----------------------------------------------------------------------------------->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">

                    </div>


                    <!-------------------ORDERED THEMED PACKS---------------------------> 
    <div class=" " id="accordion">
        <div class="collapse_headeing">
            <div class="" id="headingOne">
                {% if themed_packs %}
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Themed Packs
                    </button>
                {% endif %}
            </div>
            <div class="" id="headingTwo">
            {% if apartments or accommodations %}
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Accommodations
                    </button>
            {% endif %}
            </div>
            <div class="" id="headingThree">
                {% if cars %}
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Cars
                    </button>
                {% endif %}
        </div>
            
    </div>

        {% if themed_packs %}    
           
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <table class="table table-striped " >
                        <div class="row">
                        <thead>
                        <tr>
                    
                            <th class="AcomodationHeader">MY ITEMS</th> 
                            <th class="rate_star">
                        <span>Raiting</span>
                            <span class="hidden_star">({{ avarange_themed_pack_stars }})</span>
                            </th> 
                            <th >Price</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th></th>
                            
                        </tr>
                        </thead>
                    
                        <tbody >
                        {% for pack,star in themed_packs.items %}
                            <tr>
                            
                                <td class=""><a href="{% url 'userProfile:supplierItem' pack.id %}">{{ pack.pack_name }}</a></td>
                            
                                <td class="rate_star">
                                <span class="stars" data-rating="{{ star }}" data-num-stars="5" ></span>
                                </td>
                                <td>{{ pack.price }}$</td>
                                <td>{{ pack.start_date }}</td>
                                <td>{{ pack.end_date }}</td>
                                <td><a href="{% url 'userProfile:supplierItem' pack.id %}"> Edit </a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                </div>
                </div>
            {% endif %}
   
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                {% if accommodations %}
                    <h5 class="child_accomodation">Hotels</h5>
                    <table class="table table-striped " >
                    <div class="row">
                    <thead>
                    <tr>
                    
                        <th class="AcomodationHeader">MY ITEMS</th> 
                        <th class="rate_star">
                        
                            <span >Raiting</span>
                            <span class="hidden_star">({{ avarange_accommodation_stars }})</span>
                            
                        </th> 
                        <th>Min.Price</th>
                        <th>Num.Of.Rooms</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                
                    <tbody >
                    
                    {% for accommodation,options in accommodations.items %} 
                        <tr>
                        
                            <td class="">
                                <a href="{% url 'userProfile:supplierHotel' accommodation.id %}">{{ accommodation.name }}</a>
                            </td>
                            <td class="rate_star">
                                
                            <span class="stars" data-rating="{{ options.0 }}" data-num-stars="5" ></span>
                            </td>
                            <td>{{ accommodation.price }}$</td>
                            <td>{{ options.1.number_of_rooms }}</td>
                            <td><a href="{% url 'userProfile:supplierHotel' accommodation.id %}"> Edit</a> </td>
                            <td><a href="{% url 'userProfile:supplierHotelAdd' accommodation.id %}">Add Rooms</a></td>

                        </tr>
                    {% endfor %}
                    
                    </tbody>
                    </table>
                {% endif %}

                {% if apartments %}
                <h5 class="child_accomodation">Apartment</h5> 
                <table class="table table-striped" >
                <div class="row">
                <thead>
                <tr>
                   
                    <th class="AcomodationHeader">MY ITEMS</th> 
                    <th class="rate_star">
                    
                        <span >Stars</span>
                        <span class="hidden_star">({{ avarange_accommodation_stars }})</span>
                        
                    </th> 
                    <th>Price</th>
                    <th>Type of apartment</th>
                    <th>Capacity</th>
                    <th></th>
                </tr>
                </thead>
            
                <tbody >
                {% for apartment,options in apartments.items %} 
                    <tr>
                      
                            <td class=""><a href="{% url 'userProfile:supplierApartment' apartment.id %}">{{ apartment.name }}</a></td>
                            <td class="rate_star">
                            
                            <span class="stars" data-rating="{{ options.0 }}" data-num-stars="5" ></span>
                        </td>
                        <td>{{ apartment.price }}$</td>
                        <td>{{ options.1.choice_of_apartment }}</td>
                        <td>{{ options.1.capacity }}</td>
                            <td><a href="{% url 'userProfile:supplierApartment' apartment.id %}">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
                {% endif %}
            </div>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body">
                    <table class="table table-striped " >
                        <div class="row">
                        <thead>
                        <tr>
                          
                            <th class="AcomodationHeader">MY ITEMS</th> 
                            <th class="rate_star">
                                
                                <span  >Raiting</span>
                                <span class="hidden_star">({{ avarange_car_stars }})</span>
                            </th> 
                            <th >Price</th>
                            <th>Car Types</th>
                            <th>Num.Of.Sits</th>
                            <th></th>
                        </tr>
                        </thead>
                    
                        <tbody >
                        {% for car,start in cars.items %}
                            <tr>
                              
                                    <td class=""><a href="{% url 'userProfile:supplierCar' car.id %}">{{ car.mark }}</a></td>
                                    <td class="rate_star">
                                    <span class="stars" data-rating="{{ star }}" data-num-stars="5" ></span>
                                    </td>
                                    <td>{{ car.price }}</td>
                                    <td>{{ car.get_car_types_display }}</td>
                                    <td>{{ car.number_of_sits }}</td>
                                    <td><a href="{% url 'userProfile:supplierCar' car.id %}">Edit</a></td>
                                    <td class="delete" onclick="myFunction()" >Delete</td>
                                
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                </div>
                </div>


   

                            <!---------------- END ORDERED THEMED PACKS----------------->

                        </div>       
                         <!-- 		End of Container -->

                            <script>
                   $.fn.stars = function() {
    return $(this).each(function() {
        const rating = $(this).data("rating");
        const numStars = $(this).data("numStars");
        const fullStar = '<i class="fas fa-star"></i>'.repeat(Math.floor(rating));
        const halfStar = (rating%1!== 0) ? '<i class="fas fa-star-half-alt"></i>': '';
        const noStar = '<i class="far fa-star"></i>'.repeat(Math.floor(numStars-rating));
        $(this).html(`${fullStar}${halfStar}${noStar}`);
    });
}
                            </script>


{% endblock %}






userProfile/templates/userProfile/my_payments.html
{% extends 'userProfile/base_supplier.html' %}
{% block content %}
{% load static %}
                 <!-- Begin Page Content -->
                 <div class="container">
                    <div class="row">
                        <div class="col-xl-11 col-lg-11 col-md-11 col-sm-11">


                            
                                <!--------- title -------->
                                <div class="persontitle">
                                   <h2>Current Payments</h2>
                                </div>
                                <!------------ USER TABLE ----------->
                                 
                                <div class="boxsshadautab">
                                    <table class="table">
                                        <thead class="table_bgcolor">
                                          <tr>
                                            <th>ORDER NUMBER</th>
                                            <th>ITEM</th>
                                            <th>TITLE</th>
                                            <th>START-END DATE</th>
                                            <th>DAYS</th>
                                            <th>PRICE</th>
                                          </tr>
                                        </thead>

                                        
                                        <tbody>
                                        {% for hotel in unpaid_hotels %}
                                          <tr class="currentpay">
                                            <td>{{hotel.id}}</td>
                                            {% if hotel.hotel.hotel_name.accommodation_type == '1' %}
                                         <td>Hotel</td>
                                       {% else %}
                                        <td>Hotel</td>
                                       {% endif %}
                                            <td>{{hotel.hotel.hotel_name.name}}</td>
                                            <td>{{hotel.hotel_order_start_date}}</td>
                                            <td>{{hotel.hotel_order_end_date}}</td>
                                            <td>{{hotel.order_price}} EUR</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                   
                                        <tbody>

                                        </tbody>
                                    </table>
                                </div>







                                <div class="persontitle">
                                    <h2>Payment History</h2>
                                 </div>
                                 <!------------ USER TABLE ----------->
                                  
                                 <div class="boxsshadautab">
                                     <table class="table">
                                         <thead class="table_bgcolor">
                                           <tr>
                                            <th>ORDER NUMBER</th>
                                            <th>ITEM</th>
                                            <th>TITLE</th>
                                            <th>START-END DATE</th>
                                            <th>DAYS</th>
                                            <th>PRICE</th>
                                            <th>INVOICE</th>
                                           </tr>
                                         </thead>
 
                                         
                                         {% for hotel in paid_hotels %}
                                          <tr class="currentpay">
                                            <td>{{hotel.id}}</td>
                                            {% if hotel.hotel.hotel_name.accommodation_type == '1' %}
                                         <td>Hotel</td>
                                       {% else %}
                                        <td>Appartement</td>
                                       {% endif %}
                                            <td>{{hotel.hotel.hotel_name.name}}</td>
                                            <td>{{hotel.hotel_order_start_date}}</td>
                                            <td>{{hotel.hotel_order_end_date}}</td>
                                            <td>{{hotel.order_price}} EUR</td>
                                              <td>
                                                    <span><i class="fas fa-file-pdf"></i></span>
                                                    <a href="{% url 'userProfile:generatePdf' hotel.id %}" download="" >Download</a>
                                                </td>
                                            </tr>
                                        {% endfor %}


                                         </tbody>
                                    

                                     </table>
                                 </div>


                            

                        </div>
                    </div>
                </div>


{% endblock %}




