adminPanel/urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add,
                                          name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageedit/<int:id>', views.dashboard_default_percentage_edit,
                                                    name='dashboardDefaultPercentageEdit'),
    path('dashboarddefaultpercentagedelete/<int:id>', views.dashboard_default_percentage_delete,
                                                      name='dashboardDefaultPercentageDelete'),


    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.dashboard_interesting_facts, name='interestingFacts'),
    path('interestingfactadd', views.interesting_fact_add, name='interestingFactAdd'),
    path('interestingfactedit/<int:id>', views.interesting_fact_edit, name='interestingFactEdit'),


    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),
    path('dashboardaboutadd', views.dashboard_about_add, name='dashboardAboutAdd'),
    path('dashboardaboutedit/<int:id>', views.dashboard_about_edit, name='dashboardAboutEdit'),

    path('dashboardvendors', views.dashboard_vendors, name='dashboardVendors'),
    path('dashboardvendoradd', views.dashboard_vendor_add, name='dashboardVendorAdd'),
    path('dashboardvendordelete/<int:id>', views.dashboard_vendor_delete, name='dashboardVendorDelete'),
#components end

#orders

    path('supplier_orders/<slug:slug>', views.Suplier_orders.as_view(), name='supplierOrders'),
    path('supplier_orders/<slug:slug>/<int:id>', views.Suplier_orders.as_view(), name='supplierOrdersPost'),

#end orders

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, 
                                                      name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit,
                                                        name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

bookyToursProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import i18n
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('homepage.urls')),
    path('', include('themedTour.urls')),
    path('', include('personalTour.urls')),
    path('', include('components.urls')),
    path('', include('userProfile.urls')),
    path('', include('adminPanel.urls')),
    path('', include('supplier.urls')),
    path('', include('registration.urls')),
    path('',include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"




urlpatterns = [

path('cart/<int:id>/<int:hotel_id>', views.AddToCart.as_view(), name='addcart'),
path('cartremove/<int:product_id>',views.CartRemove.as_view(),name='cartremove'),
path('cartcar/<int:id>', views.AddToCartCar.as_view(), name='addcartcar'),

]

adminPanel/models.py
from django.db import models
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator


class Country(models.Model):
	country = CountryField()

	class Meta:
		verbose_name_plural = "Country"

	def __str__(self):
		return self.country.name


class City(models.Model):
	highway = models.ForeignKey(Country, on_delete=models.CASCADE)
	city = models.CharField(max_length=128)
	city_video = models.FileField(null=True, blank=True)
	x_c = models.IntegerField(null=True, blank=True)
	y_c = models.IntegerField(null=True, blank=True)


class FooterDescription(models.Model):
	description = models.TextField()
	address = models.CharField(max_length=100)
	email = models.EmailField()
	phoneKA = models.CharField(max_length=100, default='+995 ')
	phoneEN = models.CharField(max_length=100, default='+44 ')
	phoneFR = models.CharField(max_length=100, default='+33 ')
	phoneAZ = models.CharField(max_length=100, default='+994 ')
	phoneDE = models.CharField(max_length=100, default='+49 ')
	phoneES = models.CharField(max_length=100, default='+34 ')
	phoneHY = models.CharField(max_length=100, default='+374 ')
	phoneIT = models.CharField(max_length=100, default='+39 ')
	phoneRU = models.CharField(max_length=100, default='+7 ')

	def __str__(self):
		return self.email


#====================THEMED PACK OPTIONS============================


class ThemedPackReservation(models.Model):
	pack = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	date = models.DateField()
	quantity = models.IntegerField()
	calendar_price = models.DecimalField(max_digits=50, decimal_places=2)

	def __str__(self):
		return str(self.date)


class ThemedPackDuration(models.Model):
	duration = models.IntegerField(validators=[MinValueValidator(5)],unique=True)

	def __str__(self):
		return str(self.duration)


class ThemedPackVariety(models.Model):
	pack_variety = models.CharField(max_length=256)


	def __str__(self):
		return self.pack_variety


class ThemedPackPrice(models.Model):
	connect_pack_price = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	price_start_date = models.DateField()
	price_end_date = models.DateField()
	dynamic_price = models.DecimalField(max_digits=50, decimal_places=2)


class ThemedPackTravelersQuantity(models.Model):
	connect_pack_quantity = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	quantity_start_date = models.DateField()
	quantity_end_date = models.DateField()
	dynamic_quantity = models.IntegerField()


class CarMark(models.Model):
	car_mark = models.CharField(max_length=128)

	def __str__(self):

		return self.car_mark


#====================END THEMED PACK OPTIONS============================



class TermsAndConditions(models.Model):
	text = models.TextField()



class PrivacyPolicy(models.Model):
	text = models.TextField()


class DefaultPriceAdd(models.Model):
	add_price = models.DecimalField(max_digits=50, decimal_places=2)


class SupplierPercentageAdd(models.Model):
	supplier = models.ForeignKey(to='registration.Account', on_delete=models.CASCADE)
	percentage = models.IntegerField()

adminPanel/templates/adminPanel/dashboardAccomodation/dashboard_apartment_single.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
                <!-- Begin Page Content -->
                <div class="main_pack">
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Apartament: {{ accomodation.name }}</h1>
                    </div>

                 

                    <!-- Content Row -->

<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardAccommodationApartmentEdit' accomodation.id %}" class="form-group container-fluid" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ accomodation_form }}
                            </div>         
                        </div>
                    </tr>
                </thead>
            </table>
        </div>

    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>

<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardApartmentEdit' accomodation.id %}" class="form-group container-fluid">
        {% csrf_token %}

        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ apartment_form }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>



    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>
                          
                   
{% endblock %}

adminPanel/templates/adminPanel/dashboardAccomodation/dashboard_hotel_single.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'js/dist/js-booking-calendar.css' %}"/>
<script src="{% static 'js/dist/js-booking-calendar.js' %}"></script>
                <!-- Begin Page Content -->
                <div class="main_pack">
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Hotel: {{ accomodation.name }}</h1>
                    </div>

                    <!-- Content Row -->
<div class="acomodationSubPage">
    <form method="POST" action="{% url 'adminPanel:dashboardAccommodationApartmentEdit' accomodation.id %}" class="form-group container-fluid" enctype="multipart/form-data">
        {% csrf_token %}

        

        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                {{ accomodation_form }}
                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>



    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>

</div>


<div class="acomodationSubPage">
    {% for form in hotel_tuple %}
    <form method="POST" action="{% url 'adminPanel:dashboardHotelEdit' accomodation.id %}" 
    class="form-group container-fluid" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="contentalladd">
            <table class="table">
                <thead>
                    <tr>
                        <div class="row align-items-center change_username">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-10">
                                <tr>
                                    <th>  {{ form.room_type.label }}</th>
                                    <td>  {{ form.room_type }}   </td>
                                </tr>
                                <tr>
                                    <th>   {{ form.bed_type.label }}</th>
                                    <td>   {{ form.bed_type }}   </td>
                                </tr>
                                <tr>
                                    <th>  {{ form.family.label }}</th>
                                    <td>    {{ form.family }}   </td>
                                </tr>
                                <tr>
                                    <th>  {{ form.description.label }}</th>
                                    <td>    {{ form.description }}  </td>
                                </tr>
                                <tr>
                                    <th>  {{ form.price.label }}</th>
                                    <td>  {{ form.price }}  </td>
                                </tr>
                                <tr>
                                    <th>    {{ form.WiFi_connection.label }}</th>
                                    <td>   {{ form.WiFi_connection }}  </td>
                                </tr>
                                <tr>
                                    <th>      {{ form.parking.label }}</th>
                                    <td>   {{ form.parking }}  </td>
                                </tr>
                                <tr>
                                    <th>   {{ form.bar.label }}</th>
                                    <td>    {{ form.bar }}  </td>
                                </tr>
                                <tr>
                                    <th>   {{ form.pool.label }}</th>
                                    <td>   {{ form.pool }}  </td>
                                </tr>
                                <tr>
                                    <th>  {{ form.number_of_rooms.label }}</th>
                                    <td>   {{ form.number_of_rooms }}  </td>
                                </tr>
                                <tr id="picture_1">
                                    <th>   {{ form.picture1.label }}</th>
                                    <td >   {{ form.picture1 }}  </td>
                                </tr>
                                <tr id="picture_2">
                                    <th>   {{ form.picture2.label }}</th>
                                    <td>   {{ form.picture2 }}  </td>
                                </tr>
                                <tr id="picture_3">
                                    <th>   {{ form.picture3.label }}</th>
                                    <td>    {{ form.picture3 }} </td>
                                </tr>                         
                                <tr id="picture_4">
                                    <th>    {{ form.picture4.label }}</th>
                                    <td>    {{ form.picture4 }} </td>
                                </tr>                         
                                <tr id="picture_5">
                                    <th> {{ form.picture5.label }}</th>
                                    <td>   {{ form.picture5 }} </td>
                                </tr>                         

                            </div>
                        </div>
                    </tr>
                </thead>
            </table>
        </div>

    <div class="row  save_Delete">
                                
        <button type="submit" class="save col-xl-2 col-lg-3 col-md-3 col-sm-4 ">SAVE</button>

    </div>

    
    </form>
    {% endfor %}

</div>

    <div class="col-md-4">
        <h6 class="calendar_title">Calendar Filter</h6>
    <form method='POST' action="{% url 'adminPanel:dashboardHotelSingle' accomodation.id %}#caledendar_input" id="caledendar_input">
        {% csrf_token %}
        <input id="textfield9" name='calendar_start_date' class="form-control" type="date" id value="">
        <input id="textfield10" name='calendar_end_date' class="form-control" type="date" value="">
        <button type='submit' id="submitclick" class="btn btn-primary" >Send</button>
    </form>
    </div>

        <div class="gantt-target"></div>
  
</div>
{% for room, dates in calendar_rooms.items %}

{{ dates.0.0|date:"d-m-Y" }}
{{ dates.1.1|date:"d-m-Y" }}

{% endfor %}


<script>

    function initGantt(properties, init_scroll_position = null) {
        console.log('properties', properties);
        var gantt_chart = new Gantt(".gantt-target", properties, {

            on_click: function (task) {
                console.log(task);
            },
            on_date_change: function (task, start, end, scrollXPosition) {
                console.log(scrollXPosition);
            },
            on_progress_change: function (task, progress) {
                console.log(task, progress);
            },
            on_view_change: function (mode) {
                console.log(mode);
            },
            on_date_added: function (start, end, property, propertyIdx, xPosition, yPosition) {
                console.log('start', start);
                console.log('end', end);
                console.log('property', property);
                console.log('propertyIdx', propertyIdx);
                console.log('xPosition', xPosition);
                console.log('yPosition', yPosition);
                let props = properties;
                props[propertyIdx]['bookings'].push({
                    id: '100',
                    start: new date(),
                    end: "2022-01-01",
                    name: 'Foodddddddddddddddddd',
                    description: 'Beschreibung',
                })
                initGantt(props, xPosition)

            },
            view_mode: 'Day',
            language: 'en',
            start_date: '{{ calendar_start_date }}',
            end_date: "{{ calendar_end_date }}",
            show_label: true,
            bar_corner_radius: 0,
            column_width: 10,
            init_scroll_position: init_scroll_position,
            custom_click_on_bar: function (task) {
                console.log('custom_click_on_bar', task)
            }
        });
    }

    var properties = [ 
    {% for room, dates in calendar_rooms.items %}
        {
            name: '{{ room.room_number }}',

            bookings: [
            
                {
                    start: '{{ dates.0.0|date:"Y-m-d" }}',
                    end: '{{ dates.1.1|date:"Y-m-d" }}',
                    name: '',
                    description: 'Beschreibung',
                },
            
            
            ]
            
        },
        {% endfor %}
        
    ];

    initGantt(properties);
        let count=0
    let bar=document.querySelectorAll('.gantt .bar');
    bar.forEach(items=>{
        let colors = ['Aqua', 'Coral'];
        console.log(items)
        items.style.fill=colors[count];
        if(count<colors.length-1){
            count++
        }
        else{
            count=0
        }
    })
   
    </script>
           <!-- <script>
               let picture1=document.getElementById('picture_1')
               let picture_2=document.getElementById('picture_2')
               let picture_3=document.getElementById('picture_3')
               let picture_4=document.getElementById('picture_4')
               let picture_5=document.getElementById('picture_5')
               let id_picture1=document.getElementById("id_picture1")
                let id_picture2=document.getElementById("id_picture2")
                let id_picture3=document.getElementById("id_picture3")
                let id_picture4=document.getElementById("id_picture4")
                let id_picture5=document.getElementById("id_picture5")
               console.log(picture1.children[1].children[0].innerHTML[0]);
              
               if(picture1.children[1].children[0].innerHTML[0]!='i'){
                alert()
               }
               if(picture_2.children[1].children[0].innerHTML[0]!='i'){
                alert()
               }
               if(picture_3.children[1].children[0].innerHTML[0]!='i'){
                alert()
               }
               if(picture_4.children[1].children[0].innerHTML[0]!='i'){
                alert()
               }
               if(picture_5.children[1].children[0].innerHTML[0]!='i'){
                picture_5.style.display="none";
                id_picture4.addEventListener('change', function(){
                    picture_5.style.display="revert";
                })
               }
           </script> -->
                           
{% endblock %}

adminPanel/templates/adminPanel/dashboardAccomodation/hotels.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}


                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Hotels</h1>
                        <div class="add">
                            <a href="{% url 'adminPanel:dashboardAccomodationAdd' %}">Add Accomodation</a>
                        </div>
                    </div>

                 

                    <!-- Content Row -->
                  <div class="filters">
                    <select class  ="form-control" name="state" id="maxRows">
						 
						 
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="70">70</option>
                        <option value="100">100</option>
                        <option value="5000">Show ALL Rows</option>
                       </select>
                       <div class="tb_search">
                        <input type="text" id="search_input_all" onkeyup="FilterkeyWord_all_table()" placeholder="Search.." class="form-control">
                                </div>
                  </div>


<!------------------------------------------------------------------------------>
                  <table class="table " id= "table-id">
                      <div class="row">
                    <thead>
                        <tr>
                            <th style="width: 35px;">
                               
                            </th>
                            <th class="AcomodationHeader">Acomodation</th> 
                            <th ></th> 
                            <th ></th> 
                            <th ></th> 
                        </tr>
                    </thead>
                    <tbody >
                    {% for hotel in hotels %}
                        {% if hotel.id in hotel_notification_tuple %}
                            <tr>
                                <td class=""></td>
                                <td class="">
                                    <a href="{% url 'adminPanel:dashboardHotelSingle' hotel.id %}">{{ hotel.name }}</a>
                                </td>
                                <td> <span class="new_inner" > NEW</span></td>
                                <td class="delete confirmation" > 
                                    <a href="{% url 'adminPanel:dashboardHotelDelete' hotel.id %}">Delete Items </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td class=""></td>
                                <td class="">
                                    <a href="{% url 'adminPanel:dashboardHotelSingle' hotel.id %}">{{ hotel.name }}</a>
                                </td>
                                <td></td>
                                <td class="delete confirmation" >
                                     <a href="{% url 'adminPanel:dashboardHotelDelete' hotel.id %}">Delete Items </a> 
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                    </table>
                <!---------------------------------------------------------------------------->

                        <!--		Start Pagination -->
                        <div class='pagination-container'>
                            <nav>
                            <ul class="pagination">
                            <!--	Here the JS Function Will Add the Rows -->
                            </ul>
                            </nav>
                        </div>
                        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

                        </div> <!-- 		End of Container -->

                                    </div>
                 

                
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

{% endblock %}