adminPanel/urls.py
from django.urls import path
from . import views

app_name = "adminPanel"


urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#adminpart url 
    path('dashboardcountry', views.dashboard_country, name='dashboardCountry'),
    path('deletecountry/<int:id>', views.delete_country, name='deleteCountry'),
    path('addcountry', views.add_country, name='addCountry'),
    path('dashboardcities/<int:id>', views.dashboard_city, name='dashboardCities'),
    path('dashboardcityadd', views.dashboard_city_add, name='dashboardCityAdd'),
    path('dashboardcitysingle/<int:id>', views.dashboard_city_single, name='dashboardCitySingle'),
    path('dashboardcitydelete/<int:id>', views.dashboard_city_delete, name='dashboardCityDelete'),

    path('dashboardfooter', views.dashboard_footer, name='dashboardFooter'),

    path('dashboardtermsandconditions', views.dashboard_terms_and_conditions, name='dashboardTermsAndConditions'),

    path('dasbhoardprivacypolicy', views.dashboard_privacy_policy, name='dashboardPrivacyPolicy'),

    path('packduration', views.dashboard_themed_pack_durations, name='packDuration'),
    path('addpackduration', views.dashboard_add_themed_pack_durations, name='AddpackDuration'),
    path('deletepackduration/<int:id>', views.delete_duration, name='deletePackDuration'),

    path('packvarieties', views.dashboard_pack_varieties, name='packVarieties'),
    path('packvarietiesadd', views.dashboard_add_pack_varieties, name='packVarietiesAdd'),
    path('deletevarieties/<int:id>', views.delete_variety, name='deleteVarieties'),

    path('dashboardcarmarks', views.dashboard_car_marks, name='dashboardCarMarks'),
    path('dashboardcarmarkadd', views.dashboard_car_mark_add, name='dashboardCarMarkAdd'),
    path('deletecarmark/<int:id>', views.delete_car_mark, name='deleteCarMark'),

    path('dashboarddefaultprice', views.dashboard_default_price, name='dashboardDefaultPrice'),
    path('dashboarddefaultpercentage', views.dashboard_default_percentage, name='dashboardDefaultPercentage'),
    path('dashboarddefaultpercentageadd', views.dashboard_default_percentage_add,
                                          name='dashboardDefaultPercentageAdd'),
    path('dashboarddefaultpercentageedit/<int:id>', views.dashboard_default_percentage_edit,
                                                    name='dashboardDefaultPercentageEdit'),
    path('dashboarddefaultpercentagedelete/<int:id>', views.dashboard_default_percentage_delete,
                                                      name='dashboardDefaultPercentageDelete'),


    path('dashboardwhyus', views.dashboard_why_us, name='dashboardWhyUs'),
    path('dashboardwhyusadd', views.dashboard_why_us_add, name='dashboardWhyUsAdd'),
    path('dashboardwhyusedit/<int:id>', views.dashboard_why_us_edit, name='dashboardWhyUsEdit'),
#adminpart end

#user url

    path('admins', views.dashboard_admins, name='admins'),
    path('suppliers', views.dashboard_suppliers, name='suppliers'),
    path('customers', views.dashboard_customers, name='customers'),

    path('addadmin', views.dashboard_admin_add, name='addAdmin'),
    path('editadmin/<int:id>', views.dashboard_admin_edit, name="editAdmin"),
    path('editsupplier/<int:id>', views.dashboard_supplier_edit, name='editSupplier'),
    path('editcustomer/<int:id>', views.dashboard_customer_edit, name='editCustomer'),
    path('deleteadmin/<int:id>', views.delete_admin, name='deleteAdmin'),

#user end

#components

    path('dashboardfaq', views.dashboard_faq, name='dashboardFaq'),
    path('editfaq/<int:id>', views.faq_edit, name='editFaq'),
    path('deletefaq/<int:id>',views.faq_delete, name='deleteFaq'),
    path('addfaq',views.faq_add,name='addFaq'),

    path('homepagedestination', views.home_page_destination, name='homePageDestination'),

    path('interestingfacts', views.dashboard_interesting_facts, name='interestingFacts'),
    path('interestingfactadd', views.interesting_fact_add, name='interestingFactAdd'),
    path('interestingfactedit/<int:id>', views.interesting_fact_edit, name='interestingFactEdit'),


    path('dashboardcontacts', views.dashboard_contacts, name='dashboardContacts'),
    path('dashboardcontact/<int:id>', views.dashboard_contact, name='dashboardContact'),

    path('dashboardabout', views.dashboard_about, name='dashboardAbout'),
    path('dashboardaboutadd', views.dashboard_about_add, name='dashboardAboutAdd'),
    path('dashboardaboutedit/<int:id>', views.dashboard_about_edit, name='dashboardAboutEdit'),

    path('dashboardvendors', views.dashboard_vendors, name='dashboardVendors'),
    path('dashboardvendoradd', views.dashboard_vendor_add, name='dashboardVendorAdd'),
    path('dashboardvendordelete/<int:id>', views.dashboard_vendor_delete, name='dashboardVendorDelete'),
#components end

#orders

    path('supplier_orders/<slug:slug>', views.Suplier_orders.as_view(), name='supplierOrders'),
    path('supplier_orders/<slug:slug>/<int:id>', views.Suplier_orders.as_view(), name='supplierOrdersPost'),

#end orders

    path('dashboardpacks', views.dashboard_themed_packs, name='dashboardPacks'),
    path('dashboardsinglepack/<int:id>', views.dashboard_single_pack, name='dashboardSinglePack'),
    path('editpack/<int:id>', views.edit_themed_pack, name='editPack'),
    path('editpackdescription/<int:id>/<int:findex>', views.edit_themed_pack_description, 
                                                      name='editPackDescription'),
    path('addpack', views.add_themed_pack, name='addPack'),
    path('addthemeddaysdescriptions/<int:id>', views.add_themed_days_descriptions, name='addThemedDaysDescriptions'),
    path('themedpackreservation/<int:id>', views.themed_pack_reservation, name='themedPackReservation'),

    path('priceedit/<int:id>', views.dashboard_price_edit, name='priceEdit'),
    path('quantityedit/<int:id>', views.dashboard_quantity_edit, name='quantityEdit'),

    path('themedpackreview', views.themed_pack_review, name='themedPackReview'),
    path('editthemedpackreview/<int:id>', views.edit_themed_pack_review, name='editThemedPackReview'),
    path('deletethemedpackreview/<int:id>', views.themed_pack_review_delete, name='deleteThemedPackReview'),

    path('themedpackorder', views.themed_pack_orders, name='themedPackOrder'),
    path('addthemedpackorder', views.themed_pack_order_add, name='addThemedPackOrder'),
    path('editthemedpackorder/<int:id>', views.themed_pack_order_edit, name='editThemedPackOrder'),

    path('dashboardapartment', views.dashboard_apartments, name='dashboardApartment'),
    path('dashboardapartmentsingle/<int:id>', views.dashboard_apartment_single, name='dashboardApartmentSingle'),
    path('dashboardaccommodationapartmentedit<int:id>', views.dashboard_accommodation_apartment_edit,
                                                        name='dashboardAccommodationApartmentEdit'),
    path('dashboardapartmentedit<int:id>', views.dashboard_apartment_edit, name='dashboardApartmentEdit'),

    path('dashboardhotels', views.dashboard_hotels, name='dashboardHotels'),
    path('dashboardhotelsingle/<int:id>', views.dashboard_hotel_single, name='dashboardHotelSingle'),
    path('dashboardhoteledit<int:id>', views.dashboard_hotel_edit, name='dashboardHotelEdit'),
    path('dashboardhoteldelete/<int:id>', views.dashboard_hotel_delete, name='dashboardHotelDelete'),

    path('dashboardaccomodationadd', views.dashboard_accomodation_add, name='dashboardAccomodationAdd'),
    path('dashboardhoteladd/<int:id>', views.dashboard_hotel_add, name='dashboardHotelAdd'),
    path('dashboardapartmentadd/<int:id>', views.dashboard_apartment_add, name='dashboardApartmentAdd'),


    path('accomodationreview', views.dashboard_accomodation_reviews, name='accomodationReview'),
    path('accomodationreviewedit/<int:id>', views.dashboard_accomodation_review_edit, name='accomodationReviewEdit'),

    path('carreview', views.dashboard_car_review, name='carReview'),
    path('carreviewedit/<int:id>', views.dashboard_car_review_edit, name='carReviewEdit'),
    path('carreviewdelete<int:id>', views.delete_car_review, name='carReviewDelete'),

    path('dashboardcars', views.dashboard_cars, name='dashboardCars'),
    path('dashboardcaradd', views.dashboard_car_add, name='dashboardCarAdd'),
    path('dashboardcaredit/<int:id>', views.dashboard_car_edit, name='dashboardCarEdit'),


]

bookyToursProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import i18n
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('homepage.urls')),
    path('', include('themedTour.urls')),
    path('', include('personalTour.urls')),
    path('', include('components.urls')),
    path('', include('userProfile.urls')),
    path('', include('adminPanel.urls')),
    path('', include('supplier.urls')),
    path('', include('registration.urls')),
    path('',include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"




urlpatterns = [

path('cart/<int:id>/<int:hotel_id>', views.AddToCart.as_view(), name='addcart'),
path('cartremove/<int:product_id>',views.CartRemove.as_view(),name='cartremove'),
path('cartcar/<int:id>', views.AddToCartCar.as_view(), name='addcartcar'),

]

adminPanel/models.py
from django.db import models
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator


class Country(models.Model):
	country = CountryField()

	class Meta:
		verbose_name_plural = "Country"

	def __str__(self):
		return self.country.name


class City(models.Model):
	highway = models.ForeignKey(Country, on_delete=models.CASCADE)
	city = models.CharField(max_length=128)
	city_video = models.FileField(null=True, blank=True)
	x_c = models.IntegerField(null=True, blank=True)
	y_c = models.IntegerField(null=True, blank=True)


class FooterDescription(models.Model):
	description = models.TextField()
	address = models.CharField(max_length=100)
	email = models.EmailField()
	phoneKA = models.CharField(max_length=100, default='+995 ')
	phoneEN = models.CharField(max_length=100, default='+44 ')
	phoneFR = models.CharField(max_length=100, default='+33 ')
	phoneAZ = models.CharField(max_length=100, default='+994 ')
	phoneDE = models.CharField(max_length=100, default='+49 ')
	phoneES = models.CharField(max_length=100, default='+34 ')
	phoneHY = models.CharField(max_length=100, default='+374 ')
	phoneIT = models.CharField(max_length=100, default='+39 ')
	phoneRU = models.CharField(max_length=100, default='+7 ')

	def __str__(self):
		return self.email


#====================THEMED PACK OPTIONS============================


class ThemedPackReservation(models.Model):
	pack = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	date = models.DateField()
	quantity = models.IntegerField()
	calendar_price = models.DecimalField(max_digits=50, decimal_places=2)

	def __str__(self):
		return str(self.date)


class ThemedPackDuration(models.Model):
	duration = models.IntegerField(validators=[MinValueValidator(5)],unique=True)

	def __str__(self):
		return str(self.duration)


class ThemedPackVariety(models.Model):
	pack_variety = models.CharField(max_length=256)


	def __str__(self):
		return self.pack_variety


class ThemedPackPrice(models.Model):
	connect_pack_price = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	price_start_date = models.DateField()
	price_end_date = models.DateField()
	dynamic_price = models.DecimalField(max_digits=50, decimal_places=2)


class ThemedPackTravelersQuantity(models.Model):
	connect_pack_quantity = models.ForeignKey(on_delete=models.CASCADE, to='themedTour.ThemedPack')
	quantity_start_date = models.DateField()
	quantity_end_date = models.DateField()
	dynamic_quantity = models.IntegerField()


class CarMark(models.Model):
	car_mark = models.CharField(max_length=128)

	def __str__(self):

		return self.car_mark


#====================END THEMED PACK OPTIONS============================



class TermsAndConditions(models.Model):
	text = models.TextField()



class PrivacyPolicy(models.Model):
	text = models.TextField()


class DefaultPriceAdd(models.Model):
	add_price = models.DecimalField(max_digits=50, decimal_places=2)


class SupplierPercentageAdd(models.Model):
	supplier = models.ForeignKey(to='registration.Account', on_delete=models.CASCADE)
	percentage = models.IntegerField()

adminPanel/templates/adminPanel/adminPart/dashboard_Themed_pack_duration_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Themed Pack Duration</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:AddpackDuration' %}">
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        
                        
                        <th >
                            {{ form }}
                        </th>
                        
                        
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}
 

adminPanel/templates/adminPanel/adminPart/dashboard_Themed_pack_varieties_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add themed pack variety</h1>
            
        </div>
            <form method="POST" action="{% url 'adminPanel:packVarietiesAdd' %}">
                    {% csrf_token %}
                    
                <table class="table" id="add" >
                    <thead>
                        <tr>
                            
                            
                            <th >
                                {{ form }}
                            </th>
                            
                            
                        </tr>
                    </thead>
                    
                    </table>

                    <div class="row  save_Delete">

                    <button type="submit" class="save button_inner ">SAVE</button>

                </div>

            </form>
                          
     </div>

</div>
                 
{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_car_marks.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Car Marks</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardCarMarkAdd' %}">Add Car Mark</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "table-id">
    <thead>
        <tr>
            <th>
             
            </th>
            <th >Car Marks</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for car in car_marks %}
            <tr>
                <td></td>
                <td colspan="2"><a href=""> {{ car.car_mark }} </a></td>
                <td class="delete confirmation"><a href="{% url 'adminPanel:deleteCarMark' car.id %}">Delete</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_cities.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Select City To Change</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardCityAdd' %}">Add City</a>
        </div>
    </div>

    

    <!-- Content Row -->
        <table class="table" id= "table-id">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" class="checkAll" name="checkAll" />
                </th>
                <th >Country</th>
                <th ></th>
                <th ></th>
                
            </tr>
        </thead>
        <tbody>
            {% for city in cities %}
                <tr>
                    <td><input type="checkbox" name="item[]" value="1"></td>
                    <td colspan="2"><a href="{% url 'adminPanel:dashboardCitySingle' city.id %}"> {{ city.city }} </a></td>
                    <td class="delete"><a href="{% url 'adminPanel:dashboardCityDelete' city.id %}" class="confirmation"> Delete Country</a> </td>

                </tr>
            {% endfor %}
    
        </tbody>
    </table>
    

        <!--		Start Pagination -->
        <div class='pagination-container'>
            <nav>
            <ul class="pagination">
            <!--	Here the JS Function Will Add the Rows -->
            </ul>
            </nav>
        </div>
        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

        </div> <!-- 		End of Container -->

                    </div>
    


<!-- /.container-fluid -->


<!-- End of Main Content -->

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_country.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Select Country To Change</h1>
        <div class="add">
            <a href="{% url 'adminPanel:addCountry' %}">Add Country</a>
        </div>
    </div>

    

    <!-- Content Row -->
        <table class="table" id= "table-id">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" class="checkAll" name="checkAll" />
                </th>
                <th >Country</th>
                <th ></th>
                <th ></th>
                
            </tr>
        </thead>
        <tbody>
            {% for country in countries %}
                <tr>
                    <td><input type="checkbox" name="item[]" value="1"></td>
                    <td colspan="2"><a href="{% url 'adminPanel:dashboardCities' country.id %}"> {{ country.country.name }} </a></td>
                    <td class="delete"><a href="{% url 'adminPanel:deleteCountry' country.id %}" class="confirmation"> Delete Country</a> </td>

                </tr>
            {% endfor %}
    
        </tbody>
    </table>
    

        <!--		Start Pagination -->
        <div class='pagination-container'>
            <nav>
            <ul class="pagination">
            <!--	Here the JS Function Will Add the Rows -->
            </ul>
            </nav>
        </div>
        <!-- <div class="rows_count">Showing 11 to 20 of 91 entries</div> -->

        </div> <!-- 		End of Container -->

                    </div>
    


<!-- /.container-fluid -->


<!-- End of Main Content -->

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_default_percentage.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Default Percentages</h1>
        <div class="add">
            <a href="{% url 'adminPanel:dashboardDefaultPercentageAdd' %}">Add Default Percentage</a>
        </div>
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "">
    <thead>
        <tr>
            <th>
               
            </th>
            <th >Supplier</th>
            <th >Percentage</th>
            <th >Edit</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for percentage in percentages %}
            <tr>
                <td></td>
                <td colspan=""><a href="{% url 'adminPanel:dashboardDefaultPercentageEdit' percentage.id %}"> 
                                                                    {{ percentage.supplier.email }} </a></td>

                <td colspan=""><a href="{% url 'adminPanel:dashboardDefaultPercentageEdit' percentage.id %}"> 
                                                                    {{ percentage.percentage }}% </a></td>
                <td colspan=""><a href="{% url 'adminPanel:dashboardDefaultPercentageEdit' percentage.id %}"> 
                    Edit </a></td>
                <td class="delete confirmation">
                    <a href="{% url 'adminPanel:dashboardDefaultPercentageDelete' percentage.id %}">Delete</a>
                </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_default_percentage_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Default Percentage</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardDefaultPercentageAdd' %}">
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_default_percentage_edit.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <style>
        table#add {
            width: 68%;
        }
    </style>
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Percentage</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_interesting_fact_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Fact</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_terms_and_conditions.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<script src="https://cdn.ckeditor.com/ckeditor5/11.0.1/classic/ckeditor.js"></script>
<div class="main_pack">
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Terms and Conditions</h1>

                    </div>

                   
                    <form action="{% url 'adminPanel:dashboardTermsAndConditions' %}" method="POST">
                        
                    {% csrf_token %}

                     
                    <table class="table table_terms" id="" >
                        
                            <tr>
                                
                                <th style="width: 25%;" ></th>
                                <td >                                  
                                    {{ form.text }}
                                 </td>                             
                               
                            </tr>
                            
                     </table>
                     
                    <div class="row  save_Delete">

                        <button type="submit" class="save button_inner ">SAVE</button>
                    
                    </div>
                     
                    </form>

        
                  
                        </div> <!-- 		End of Container -->

                                    </div>
                 

                                    <script>
                                        ClassicEditor
                                            .create( document.querySelector( '#editor' ) )
                                            .catch( error => {
                                                console.error( error );
                                            } );
                                    </script>
                <!-- /.container-fluid -->

            
            <!-- End of Main Content -->

 {% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_why_us.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Why Us</h1>
        {% if number_of_content < 3 %}
            <div class="add">
                    <a href="{% url 'adminPanel:dashboardWhyUsAdd' %}">Add Why Us</a>
            </div>
        {% endif %}
    </div>

                 

    <!-- Content Row -->
    <table class="table" id= "table-id">
    <thead>
        <tr>
            <th>
               
            </th>
            <th >Why Us</th>
            <th ></th>
            <th ></th>
            
        </tr>
    </thead>
    <tbody>
        
        {% for us in why_us %}
            <tr>
                <td></td>
                <td colspan="2"><a href="{% url 'adminPanel:dashboardWhyUsEdit' us.id %}"> {{ us.title }} </a></td>
                <td><a href="{% url 'adminPanel:dashboardWhyUsEdit' us.id %}">Edit</a> </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>

</div> 

 {% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_why_us_add.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Why Us</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardWhyUsAdd' %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}

adminPanel/templates/adminPanel/adminPart/dashboard_why_us_edit.html
{% extends 'adminPanel/admin_menu.html' %}
{% load static %}
{% block content %}
<div class="main_pack">
    <style>
        table#add {
            width: 68%;
        }
    </style>
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Why Us</h1>
        </div>

        

        <!-- Content Row -->
        <form method="POST" action="{% url 'adminPanel:dashboardWhyUsEdit' why_us.id %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            <table class="table" id="add" >
                <thead>
                    <tr>
                        <th >
                            {{ form }}
                        </th>
                    </tr>
                </thead>
                
            </table>

            <div class="row  save_Delete">
                
            <button type="submit" class="save button_inner ">SAVE</button>   

            </div>
                
        </form>
    </div>           
</div> 

{% endblock %}